/* Autogenerated file */

#include "regs_st.h"
namespace Regs {
const char* GetString(MMU_BANK val)
{
	if (val==0) return "128K";
	if (val==1) return "512K";
	if (val==2) return "2MB";
	if (val==3) return "reserved";
	return "?";
}
const char* GetString(RESOLUTION val)
{
	if (val==0) return "ST-Low";
	if (val==1) return "ST-Medium";
	if (val==2) return "ST-High";
	return "?";
}
const char* GetString(SYNC_RATE val)
{
	if (val==0) return "60Hz";
	if (val==1) return "50Hz";
	return "?";
}
const char* GetString(SYNC_TYPE val)
{
	if (val==0) return "Internal Sync";
	if (val==1) return "External Sync";
	return "?";
}
} // namespace
